import { Product, Order, OrderStatus, PaymentMethod, CarModel } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Front Bumper Assembly',
    sku: 'M3-FBA-001',
    price: 450,
    currency: 'USD',
    stock: 12,
    category: CarModel.MODEL_3,
    image: 'https://picsum.photos/200',
    description: 'Original OEM front bumper for Model 3 (2017-2023). Primed and ready for paint.',
  },
  {
    id: 'p2',
    name: 'Falcon Wing Door Sensor',
    sku: 'MX-FWD-S02',
    price: 120,
    currency: 'USD',
    stock: 4,
    category: CarModel.MODEL_X,
    image: 'https://picsum.photos/201',
    description: 'Ultrasonic sensor for Falcon Wing doors.',
  },
  {
    id: 'p3',
    name: '17" Touchscreen Display',
    sku: 'MS-TS-003',
    price: 1200,
    currency: 'USD',
    stock: 2,
    category: CarModel.MODEL_S,
    image: 'https://picsum.photos/202',
    description: 'MCU2 Upgrade kit touchscreen replacement.',
  },
  {
    id: 'p4',
    name: 'Rear Tail Light (Left)',
    sku: 'M3-RTL-L04',
    price: 220,
    currency: 'USD',
    stock: 8,
    category: CarModel.MODEL_3,
    image: 'https://picsum.photos/203',
    description: 'European spec amber turn signal tail light.',
  },
  {
    id: 'p5',
    name: 'Cabin Air Filter (HEPA)',
    sku: 'MY-CAF-005',
    price: 45,
    currency: 'USD',
    stock: 150,
    category: CarModel.MODEL_Y,
    image: 'https://picsum.photos/204',
    description: 'Bioweapon defense mode compatible filter.',
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-7782',
    customerName: 'Oleksandr Kovalenko',
    customerEmail: 'alex.kov@example.com',
    customerPhone: '+380501234567',
    novaPostBranch: 'Kyiv, Branch #12',
    paymentMethod: PaymentMethod.IBAN,
    status: OrderStatus.PENDING,
    date: '2024-05-20T10:30:00Z',
    total: 450,
    currency: 'USD',
    items: [
      { productId: 'p1', productName: 'Front Bumper Assembly', quantity: 1, priceAtPurchase: 450 },
    ],
  },
  {
    id: 'ORD-7783',
    customerName: 'Maria Petrenko',
    customerEmail: 'maria.p@example.com',
    customerPhone: '+380671234567',
    novaPostBranch: 'Lviv, Branch #5',
    paymentMethod: PaymentMethod.CARD,
    status: OrderStatus.SHIPPED,
    date: '2024-05-19T14:15:00Z',
    total: 165,
    currency: 'USD',
    items: [
      { productId: 'p5', productName: 'Cabin Air Filter (HEPA)', quantity: 1, priceAtPurchase: 45 },
      { productId: 'p2', productName: 'Falcon Wing Door Sensor', quantity: 1, priceAtPurchase: 120 },
    ],
  },
  {
    id: 'ORD-7784',
    customerName: 'Ivan Boiko',
    customerEmail: 'ivan.b@example.com',
    customerPhone: '+380631234567',
    novaPostBranch: 'Odesa, Branch #1',
    paymentMethod: PaymentMethod.CASH_ON_DELIVERY,
    status: OrderStatus.COMPLETED,
    date: '2024-05-18T09:00:00Z',
    total: 1200,
    currency: 'USD',
    items: [
      { productId: 'p3', productName: '17" Touchscreen Display', quantity: 1, priceAtPurchase: 1200 },
    ],
  },
  {
    id: 'ORD-7785',
    customerName: 'Tetiana Shevchenko',
    customerEmail: 'tanya.sh@example.com',
    customerPhone: '+380991234567',
    novaPostBranch: 'Dnipro, Branch #22',
    paymentMethod: PaymentMethod.CARD,
    status: OrderStatus.PROCESSING,
    date: '2024-05-20T11:45:00Z',
    total: 220,
    currency: 'USD',
    items: [
      { productId: 'p4', productName: 'Rear Tail Light (Left)', quantity: 1, priceAtPurchase: 220 },
    ],
  },
];